### DISCUSSION TITLE
Integration of carbon aware SDK with Impact Framework

### DISCUSSION THREAD

**Discussion by srini1978** [Green-Software-Foundation/hack#26] [Develop an Idea]
Today the carbon aware SDK is a mature open source project. The carbon aware SDK integrates with backend APIs- Watt Time and Electricity maps and helps identify green regions for running cloud workloads. The 2 techniques that carbon aware SDK enables are region shifting and time shifting.  The resultant of these techniques helps in reducing the "I" value of the SCI (Software carbon intensity) formula. 

The idea here is to integrate Impact framework with carbon aware SDK. We could embed carbon aware SDK (either as a SDK or API) in the computation pipeline of Impact framework such that the SCI-O pipeline runs off of carbon aware SDK.   

## Prize category
_Help the participant understand which of the prize categories this idea would best fit_

- [x] Best Model
- [ ] Best Content
- [ ] Beyond Carbon
- [ ] Best contribution to the framework

## User Story
_Describe the benefits of this change, ideally in the following format:_

As a developer, I would like to link embed carbon aware SDK in the manifest file of  Impact framework so that the carbon intensity is calculated by the SDK. 

## Rationale
Provide the relevant background information to understand why this is a useful thing to work on

*This is where you can provide more details that help the reader understand why you want to make this change*

## Impact
Finish this scentance: "If this idea is successful implemented the ....."

## Implementation guidelines
- If there are specific implementation details that are REQUIRED or PREFERRED please describe them here
*e.g. this model MUST conform to the `ModelPlugin` interface*
*e.g. this feature MUST be part of the supercomputer module*
*e.g. this feature SHOULD be be a model plugin*

## Difficulty
_Provide an assessment of the expected difficulty **from 1-5** to help hackers find tasks at their preferred skill level_
2/5
## Scope Of Work
_List some of the tasks that will be required to implement this idea_

- [ ] A new model plugin
- [x] A new feature in an existing model plugin
- [x] A manifest file will have to be written
- [x] Implement test cases
- [ ] A new feature to the framework itself (the cli tool)
- [ ] It will require changes to the documentation

## Examples and resources
[IF docs](https://if.greensoftware.foundation/)
[Model building tutorial](https://if.greensoftware.foundation/tutorials/how-to-build-models)

## Manifest File
Provide a dummy Mmnifest file to help the implementer understand how this functionality will be executed, provide them with the necessary data, observations and structure so they can move fast with development.

```yaml
name: nesting-demo
description:
tags:
  kind: web
  complexity: moderate
  category: cloud
initialize:
  models:
    - name: teads-curve
      model: TeadsCurveModel
      path: "@grnsft/if-unofficial-models"
    - name: sci-e
      model: SciEModel
      path: "@grnsft/if-models"
    - name: sci-m
      path: "@grnsft/if-models"
      model: SciMModel
    - name: sci-o
      model: SciOModel
      path: "@grnsft/if-models"
    - name: sci
      model: SciModel
      path: "@grnsft/if-models"
graph:
  children:
    child: # an advanced grouping node
      pipeline:
        - teads-curve
        - sci-e
        - sci-m
        - sci-o
        - sci
      config:
        teads-curve:
          thermal-design-power: 65
        sci-m:
          total-embodied-emissions: 251000 # gCO2eq
          time-reserved: 3600 # 1 hour in s
          expected-lifespan: 126144000 # 4 years in seconds    
          resources-reserved: 1 
          total-resources: 1 
       sci:
          functional-unit-duration: 1 
          functional-duration-time: ''
          functional-unit: requests # factor to convert per time to per f.unit
      children:
        child-1:
          inputs:
            - timestamp: 2023-07-06T00:00
              duration: 10
              cpu-util: 50
              e-net: 0.000811 #kwh     
              requests: 380
        child-2:
          inputs: 
            - timestamp: 2023-07-06T00:00
              duration: 10
              cpu-util: 33
              e-net: 0.000811 #kwh     
              requests: 380

```

**Comment by srini1978** [comment]
[carbonawareSDK](https://github.com/Green-Software-Foundation/if/issues/216)

**Comment by jawache** [comment]
@srini1978 there are two ways a CA SDK plugin could be used in the IF, as far as I can see:

1. To be a source of `grid-carbon-intensity` data. If you are already using CA SDK in your organization and have configured various data sources inside it already, makes sense to use that instead of directly connecting to `watttime` or `electricity-maps`

```yaml
      pipeline:
        - teads-curve
        - casdk-grid-carbon-intensity # returns grid-carbon-intensity for this region/location etc...
```
2. To simulate what would happen if this component was run in a carbon-aware way (time/region shifted), so something like so:

```yaml
config:
  carbon-aware:
    time-shift: +-4hr
    region-shift: us-only
pipeline:
  - carbon-aware
```

What's your thoughts?
