### DISCUSSION TITLE
Generic CPU Power Curve model

### DISCUSSION THREAD

**Discussion by pazbardanl** [Green-Software-Foundation/hack#37] [Develop an Idea]
@jawache 

## Prize category

- [x] Best Model
- [ ] Best Content
- [ ] Beyond Carbon
- [ ] Best contribution to the framework

## User Story
- As an **IF user**, I want **to be able to create and use custom CPU power curves in IF** so that **I could calculate carbon emissions of my system based on it's specific power consumption model**

## Rationale
Based on our work on the _Intel model_ (aka _IEE = "Intel Energy Estimator"_) we know that many clients (private, OEMs and others) use customized systems where the power consumption characteristics (aka power curves) may differ from the generic ones provided by manufacturers (if any). The idea here is to provide a model where users will only need to plug in their custom power curve (as a data file) and have the model carry the burden of energy calculations, among others, at runtime.
Such a model would be backed by a script that will generate a power curve on given system.

## Impact
Successfully implementing this idea will:

1. Significantly **simplify getting started with IF**, for those wanting to have a pipeline that accurately reflects their specific system modifications and customizations. Acknowledging the importance of CPU modeling in the manifest file, we can see how this will improve onboarding of such users, as they **will be able to create their own power curves** and then **only provide the resulting data to the model, without writing any code**.
2. Increase **transparency under a unified standard**: once all CPU-modeling users use the same Generic CPU Power Curve generation script and model, we know that while the data naturally **differs** between each, the process of creating the power curves and calculations done based on those curves are the **same** across all users. Even if users can't share their data (power curves), we at least have transparency over their computations.

## Implementation guidelines
* this model MUST conform to the `ModelPlugin` interface*
* this model SHOULD define default requirements from the input power curve file, for example: CSV format, with mapping of CPU utilization [%] to power [kW].
* This model SHOULD be backed up by a script that generates a power curve on host system, using a standard (set of) benchmark(s)
* this model MUST include the following in its implementation: (1) parsing of an external power curve file, and building in-memory representation of the curve to use for calculations at runtime (2) input validation (3) interpolation: while the input power curve have discrete utilization->power pairs, the inputs to the model may be any (continuous) value. The model should handle that by (linearly?) interpolating utilization and power values.
* this model COULD be able to represent more than 1 CPU, by taking multiple input files or taking a single file representing power curves for multiple CPUs.

## Difficulty
4/5

## Scope Of Work

- [x] A new model plugin + **documentation**
- [ ] A new feature in an existing model plugin
- [x] A manifest file will have to be written (**as an example**)
- [ ] Implement test cases
- [ ] A new feature to the framework itself (the cli tool)
- [ ] It will require changes to the documentation

## Manifest File
Provide a dummy Mmnifest file to help the implementer understand how this functionality will be executed, provide them with the necessary data, observations and structure so they can move fast with development.

```yaml
name: nesting-demo
description:
tags:
  kind: web
  complexity: moderate
  category: on-premise
initialize:
  models:
    - name: generic-power-curve
      model: generic-power-curve
      path: "@grnsft/if-unofficial-models"
      ...
      ...
graph:
  children:
    child:
      pipeline:
        - generic-power-curve
       ...
       ...
      config:
       - generic-power-curve
          power-curves:
               - path/to/custom/power/curve/A.csv
               - path/to/custom/power/curve/B.csv
               - path/to/custom/power/curve/C.csv
      children:
          inputs:
            - timestamp: 2023-07-06T00:00
              duration: 10
              cpu-util: 50
              ...
              ...
            - timestamp: 2023-07-06T00:00
              duration: 10
              cpu-util: 33
    
```
