### ISSUE TITLE
Measure the carbon impact of a website

### ISSUE THREAD

**Issue by jmcook1186** [Green-Software-Foundation/hack#10]
Please use this template to suggest an idea that people can try to implement as part of Carbon Hack 24. **Provide as much detail as possible**. If someone else submitted an idea but you feel you can do a better job of explaining, please go ahead and submit again.

## Prize category
_Help the participant understand which of the prize categories this idea would best fit_

- [x] Best Model
- [ ] Best Content
- [ ] Beyond Carbon
- [ ] Best contribution to the framework

## User Story
As a web developer I want to know how much carbon is consumed when people visit my website.

## Rationale

The carbon impact of a website is the result of the deployment and hosting infrastructure and the cost of serving the website content. These can be calculated using existing models in the IF repositories. However, calculating the impact of a real website requires carefully configuring the manifest file and choosing the right models as well as finding accurate input data.

## Impact
If this idea is successful implemented then the IF will be producing actionable insights for a real world product.

## Implementation guidelines

- The manifest file MUST run successfully using the IF

## Difficulty
2/5

## Scope Of Work
_List some of the tasks that will be required to implement this idea_

- [ ] A new model plugin
- [ ] A new feature in an existing model plugin
- [x] A manifest file will have to be written
- [ ] Implement test cases
- [ ] A new feature to the framework itself (the cli tool)
- [ ] It will require changes to the documentation

## Examples and resources
_Provide any links to prior discussions, similar code, examples, pseudocode, diagrams or anything else than can help the hacker understand the task_

## Manifest File

The following manifest file is a demo that shows a valid structure - you will need to update it for your website!

```yaml
name: nesting-demo
description:
tags:
  kind: web
  complexity: moderate
  category: on-premise
initialize:
  models:
    - name: teads-curve
      model: TeadsCurveModel
      path: "@grnsft/if-unofficial-models"
    - name: sci-e
      model: SciEModel
      path: "@grnsft/if-models"
    - name: sci-m
      path: "@grnsft/if-models"
      model: SciMModel
    - name: sci-o
      model: SciOModel
      path: "@grnsft/if-models"
    - name: sci
      model: SciModel
      path: "@grnsft/if-models"
graph:
  children:
    child: # an advanced grouping node
      pipeline:
        - teads-curve
        - sci-e
        - sci-m
        - sci-o
        - sci
      config:
        teads-curve:
          thermal-design-power: 65
        sci-m:
          total-embodied-emissions: 251000 # gCO2eq
          time-reserved: 3600 # 1 hour in s
          expected-lifespan: 126144000 # 4 years in seconds    
          resources-reserved: 1 
          total-resources: 1 
        sci-o:
          grid-carbon-intensity: 457 # gCO2/kwh
        sci:
          functional-unit-duration: 1 
          functional-duration-time: ''
          functional-unit: requests # factor to convert per time to per f.unit
      children:
        child-1:
          inputs:
            - timestamp: 2023-07-06T00:00
              duration: 10
              cpu-util: 50
              e-net: 0.000811 #kwh     
              requests: 380
        child-2:
          inputs: 
            - timestamp: 2023-07-06T00:00
              duration: 10
              cpu-util: 33
              e-net: 0.000811 #kwh     
              requests: 380

```
