### ISSUE TITLE
E2E Integration with Prometheus

### ISSUE THREAD

**Issue by pazbardanl** [Green-Software-Foundation/hack#14]
## Prize category

- [x] Best Model
- [ ] Best Content
- [ ] Beyond Carbon
- [ ] Best contribution to the framework

## User Story

- As an **IF user**, I want to to use IF to **pull input metrics from** and **push carbon emission data into Prometheus** so that **I can view and analyze Carbon emissions as a standard metric**

## Rationale
Carbon emissions are a metric. It's data we produce using the Impact Framework. As such, we would want it to be stored and ready to use just like any other metric that is being monitored by Devops, Site Reliability Engineers an others.
On the same note: we should be able to fetch (import) metric data from the same storage to use as input to IF.

## Impact
Looking forward to stuff being built on top of IF (Beta?), successfully implementing this idea will put it in a great starting point for being used to enhance observability. 
A ready-to-use manifest file, backed by proper Prometheus importer and exported models, will:
(1) Encourage people to look at carbon emission as a metric to monitor, alert and make decisions based-of.
(2) Show how IF caters to the common use case of Observability. 

## Implementation guidelines
- models built for this task MUST conform to the ModelPlugin interface

## Difficulty
4/5

## Scope Of Work
- 2 new models: Prometheus importer and exporter
- A local instance of Prometheus with CPU data (could be random/fake static data) 
- A manifest file where the pipeline starts with the Prometheus importer and closes with the Prometheus exporter
- IDEALLY a demo, visualizing inputs (like CPU util) and output (carbon) on the same dashboard, emphasizing that data for both was extracted from the same Prometheus instance

- [x] A new model plugin
- [ ] A new feature in an existing model plugin
- [x] A manifest file will have to be written
- [ ] Implement test cases
- [ ] A new feature to the framework itself (the cli tool)
- [ ] It will require changes to the documentation

## Examples and resources
[getting started with Prometheus](https://prometheus.io/docs/prometheus/latest/getting_started/)

## Manifest File

```yaml
name: prometheus-e2e-demo
description:
tags:
  kind: web
  complexity: moderate
  category: on-premise
initialize:
  models:
    - name: prometheus-importer
      model: PrometheusImporter
      path: "@grnsft/if-unofficial-models"
   ...
   ...
   ...
    - name: prometheus-exporter
      model: PrometheusExporter
      path: "@grnsft/if-unofficial-models"
graph:
  children:
    child: # an advanced grouping node
      pipeline:
        - prometheus-importer
       ...
       ...
       ...
        - prometheus-exporter
      config:
        prometheus-importer:
          {prometheus connection info, data source / table from which to fetch input data}
       ...
       ...
       ...
        prometheus-exporter:
          {prometheus connection info, data source / table to which to push output data}
        
      children:
        child-1:
          inputs:

```
