### ISSUE TITLE
[Idea] ....Ability to run the models that are part of the Impact framework in parallel

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/hack#23]
## Prize category
_Help the participant understand which of the prize categories this idea would best fit_

- [ ] Best Model
- [ ] Best Content
- [ ] Beyond Carbon
- [X ] Best contribution to the framework

## User Story
As a developer I want to provide the capability in the framework to be able to run the models in the computation pipeline in parallel so as to improve the response time for calculation of the impact metric. 

## Rationale
An Impact graph consists of multiple nodes and each node corresponds to a software component. The current way of working of the impact framework is that the impl files from each of the nodes are fed through the computation pipeline serially. In case there is no dependency between the nodes in the graph, there is an opportunity to run the impact framework in parallel so that the computation happens in parallel as well. In case parallel processing is difficult, we can explore asynchronous computation as well. 

The aggregation pipeline could be  a pipeline that can wait for values  from all the nodes to be complete. 

## Impact
Finish this scentance: "If this idea is successful implemented the ....."

## Implementation guidelines
- If there are specific implementation details that are REQUIRED or PREFERRED please describe them here
*e.g. this model MUST conform to the `ModelPlugin` interface*
*e.g. this feature MUST be part of the supercomputer module*
*e.g. this feature SHOULD be be a model plugin*

## Difficulty
2/5

## Scope Of Work
_List some of the tasks that will be required to implement this idea_

- [ ] A new model plugin
- [ ] A new feature in an existing model plugin
- [ X ] A manifest file will have to be written
- [ X ] Implement test cases
- [ X ] A new feature to the framework itself (the cli tool)
- [ X ] It will require changes to the documentation

## Examples and resources
_Provide any links to prior discussions, similar code, examples, pseudocode, diagrams or anything else than can help the hacker understand the task_

## Manifest File
Provide a dummy Mmnifest file to help the implementer understand how this functionality will be executed, provide them with the necessary data, observations and structure so they can move fast with development.

```yaml
name: nesting-demo
description:
tags:
  kind: web
  complexity: moderate
  category: on-premise
initialize:
  models:
    - name: teads-curve
      model: TeadsCurveModel
      path: "@grnsft/if-unofficial-models"
    - name: sci-e
      model: SciEModel
      path: "@grnsft/if-models"
    - name: sci-m
      path: "@grnsft/if-models"
      model: SciMModel
    - name: sci-o
      model: SciOModel
      path: "@grnsft/if-models"
    - name: sci
      model: SciModel
      path: "@grnsft/if-models"
graph:
  children:
    child: # an advanced grouping node
      pipeline:
        - teads-curve
        - sci-e
        - sci-m
        - sci-o
        - sci
      config:
        teads-curve:
          thermal-design-power: 65
        sci-m:
          total-embodied-emissions: 251000 # gCO2eq
          time-reserved: 3600 # 1 hour in s
          expected-lifespan: 126144000 # 4 years in seconds    
          resources-reserved: 1 
          total-resources: 1 
        sci-o:
          grid-carbon-intensity: 457 # gCO2/kwh
        sci:
          functional-unit-duration: 1 
          functional-duration-time: ''
          functional-unit: requests # factor to convert per time to per f.unit
      children:
        child-1:
          inputs:
            - timestamp: 2023-07-06T00:00
              duration: 10
              cpu-util: 50
              e-net: 0.000811 #kwh     
              requests: 380
        child-2:
          inputs: 
            - timestamp: 2023-07-06T00:00
              duration: 10
              cpu-util: 33
              e-net: 0.000811 #kwh     
              requests: 380

```
