### ISSUE TITLE
Starter Pack for Startups

### ISSUE THREAD

**Issue by Ches-ctrl** [Green-Software-Foundation/hack#61]
### Type of project

Building a plug-in for Impact Framework

### Overview

A simple-as-possible plugin that gets startups an 80/20 view of the carbon impact of their software without writing any code.

How it could work:
1. Takes standard inputs via a GUI/website
2. Generates an `impl` file
3. Runs the IF model
4. Reads the `ompl` file
5. Displays the outputs to the user

How this could be extended:
a) Graphical displays of information
b) Benchmarking versus other startups
c) Analyses sensitivity to inputs
c) Suggests & prioritises options to reduce emissions
d) Suggests options for offsetting

### Questions to be answered

Key questions:
- Key standard inputs to ask for
- Best way of interfacing with the user
- Decisions over standard settings (choice of models etc.)

### Have you got a project team yet?

No, we would like your help to find team-mates

### Terms of Participation

- [X] I agree to the hackathon [Rules & Terms](https://github.com/Green-Software-Foundation/hack/wiki/Rules-and-Terms) and [Code of Conduct](https://github.com/Green-Software-Foundation/hack/wiki/Code-of-Conduct)

**Comment by jawache** [comment]
Hi @Ches-ctrl, great to see you here! We discussed this in the hackathon Q&A today https://www.youtube.com/watch?v=KjMBuz252pE

Overall, the approach is great, and I can see where you're going with this; however, in its current form, it wouldn't be something that fits into one of the hackathon prize categories. It's more like an application that sits alongside or on top of Impact Framework, which we expect people to build in the near future, but we're a little early for now, and we don't have a prize category for it.

As you'll find in the video, we zoomed into the part in the proposal about "Suggests options for offsetting" and spent a while discussing that. That could be built as a plugin which would slot in very well with the ecosystem of plugins that currently and will soon be built.

I think a plugin which takes some inputs (energy or carbon), and some config could be built which then tries to figure out how much it would cost you to offset your application to the level and quality of offsets that you want to achieve.

So a pipeline like this perhaps

```yaml
      pipeline:
        - azure-importer
        - cloud-instance-metadata
        - teads-curve # at this point in the pipeline you'd have energy
        - energy-offsets # <-- the plugin you'll build! How many RECs do you need to buy to offset the energy consumed by your application?
      config:
        energy-offsets:
          target: 95 # Your target is 95% offset
          methodology: yearly # yearly or hourly methodology.
          max-pay: £2 per kWh # some aspect of quality? RECs come in many forms, with varying quality and sustainability claims that can be made
```

Some literature that might help is this: https://learn.greensoftware.foundation/climate-commitments#100-renewable I'm also fairly sure there are APIs to get prices for RECs (they might be $$, not sure)

If not energy offsets, then carbon offsets might be easier. There are lots of APIs for that. Take any carbon value that's input in an observation and figure out how to offset with a similar type of config. Some measure of the standard of offset features you'd accept. A great piece of work from Microsoft is this: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE4MDlc. It breaks down carbon offsets into cost and durability, which is often an ignored feature. Durability is the length of time the carbon is going to be extracted from the atmos; carbon offsets that are cheaper usually have low durability, and carbon offsets that are more expensive have longer durability. But when we make claims of 100% carbon neutral, there is no transparency regarding how long the carbon is out of the atmosphere. (planting a tree has a durability of about 100 years, and some sort of air carbon capture and storage has a durability of 10,000 years)

```yaml
      pipeline:
        - azure-importer
        - cloud-instance-metadata
        - teads-curve # at this point in the pipeline you'd have energy
        - sci-e
        - sci-o # you now have carbon
        - carbon-offsets # <-- the plugin you'll build! How many carbon offsets do you need to buy?
      config:
        carbon-offsets:
          target: 95 # Your target is 95% offset
          durability: how many years do you want the carbon to be offset for
          ???
```
